const C = {
    ADD_WORD: "ADD_WORD",
    APPEND_TRANSLATION_BUFFER: "APPEND_TRANSLATION_BUFFER",
    APPEND_TRANSLATION_QUEUE: "APPEND_TRANSLATION_QUEUE",
    DIRECTION: {
        LEFT: "LEFT",
        RIGHT: "RIGHT"
    },
    DISPLAY_TRANSLATION: "DISPLAY_TRANSLATION",
    DOC_VIEWER_OPTIONS: {
        ADD_VOCAB: "ADD_VOCAB",
        BOOKMARKS: "BOOKMARKS",
        DEFAULT: "DEFAULT",
        TRANSLATION_COORDINATOR: "TRANSLATION_COORDINATOR"
    },
    DOCUMENT_SELECTOR: "DOCUMENT_SELECTOR",
    DOCUMENT_VIEWER: "DOCUMENT_VIEWER",
    FILTER_TRANSLATION_QUEUE: "FILTER_TRANSLATION_QUEUE",
    FINISHED_LOADING: "FINISHED_LOADING",
    HIGHLIGHT: "HIGHLIGHT",
    LINE_BOUNDARY: {
        END: "END",
        START: "START"
    },
    LIST_DOCUMENTS: "LIST_DOCUMENTS",
    NEXT_PAGE: "NEXT_PAGE",
    NO_ACTION: "NO_ACTION",
    PREVIOUS_PAGE: "PREVIOUS_PAGE",
    RESET_TEXT_BOUNDARY: "RESET_TEXT_BOUNDARY",
    RESET_TRANSLATIONS: "RESET_TRANSLATIONS",
    SELECT_DOCUMENT: "SELECT_DOCUMENT",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_INTERACTION: "SET_INTERACTION",
    SET_OPTION: "SET_OPTION",
    SET_PAGE_RANGE: "SET_PAGE_RANGE",
    SET_TEXT_BOUNDARY: "SET_TEXT_BOUNDARY",
    TEXT_FINISH: "TEXT_FINISH",
    TEXT_START: "TEXT_START",
    TRANSLATION_QUEUE_MAX_SIZE: 25,
    TRANSLATION_VIEWER: "TRANSLATION_VIEWER",
    UNHIGHLIGHT: "UNHIGHLIGHT"
}

export default C